services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  api:
    build:
      context: .
    container_name: fastapi-application
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    depends_on:
      - redis
    