services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  backend:
    build:
      context: .
    container_name: fastapi-application
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    